### ISSUE TITLE
Train error in Classification

### ISSUE THREAD

**Issue by manuelcugliari** [team-daniel/KAN#2]
During the train in the classification section I get "[Error]: Target size (torch.Size([279958])) must be the same as input size (torch.Size([279958, 1]))"

**Comment by team-daniel** [comment]
Thanks for raising this. Can you provide me with the code to replicate this issue on my end. Once you do this I will be able to fix this for you 😃

**Comment by team-daniel** [comment]
This is assumed to be no longer an issue due to no response, ping me if it still isn't working
