### ISSUE TITLE
The selection rules of parameters should be further explored.

### ISSUE THREAD

**Issue by doouya** [team-daniel/KAN#4]
The performance of KAN is not satisfactory, especially on the housing price dataset, considering the difficulty and efficiency of parameter adjustment, although I have tried to adjust the hyperparameters. For example, random forest can easily and efficiently beat KAN. But this is not a reason for us to lose, because many models that claim to have high performance are more sensitive to parameters. The selection rules of parameters should be further explored.

**Comment by team-daniel** [comment]
The repo was ONLY to show how to quickly set up and use experiments using KANs. I have not claimed anything regarding performance or param efficiency. If you are looking for recommendations regarding params, I suggest the original author's site:

- https://kindxiaoming.github.io/pykan/index.html

I planned on doing another deep dive into sensitivity of params at some point in the future.
