### ISSUE TITLE
Request to update the code

### ISSUE THREAD

**Issue by JianxianWANG** [team-daniel/KAN#8]
Dear Daniel

Hope this message finds you well.
I'm encountering many errors while running your code. Could you update the code again?

Best Regards,
John

**Comment by team-daniel** [comment]
Hi John,

Thanks for the nudge, PyKAN has just gone through some syntax updates. I have fixed the code and the notebooks should run again now :)

Best, 
- Dan

**Comment by JianxianWANG** [comment]
Hi Daniel,

Thank you so much for your prompt response and the fix! I really appreciate your help in resolving the issue with PyKAN. The notebooks are now running smoothly, and your support has been invaluable in getting things back on track.

Looking forward to continuing working with PyKAN, and thanks again for your assistance!

Best regards,
John
